-- Insert Directors
INSERT INTO Directors (name, image_name) VALUES
('Robert Zemeckis', 'robert_zemeckis'),
('Frank Darabont', 'frank_darabont'),
('Francis Ford Coppola', 'francis_ford_coppola'),
('Anthony Minghella', 'anthony_minghella'),
('Tom Hooper', 'tom_hooper'),
('Steven Spielberg', 'steven_spielberg'),
('David Fincher', 'david_fincher'),
('Roberto Benigni', 'roberto_benigni'),
('Peter Weir', 'peter_weir'),
('John McTiernan', 'john_mctiernan'),
('George Miller', 'george_miller'),
('Lana Wachowski', 'lana_wachowski'),
('Christopher Nolan', 'christopher_nolan'),
('Ridley Scott', 'ridley_scott'),
('Quentin Tarantino', 'quentin_tarantino'),
('James Cameron', 'james_cameron'),
('Mel Gibson', 'mel_gibson'),
('Martin Scorsese', 'martin_scorsese');

-- Insert Actors
INSERT INTO Actors (name, image_name) VALUES
('Tom Hanks', 'tom_hanks'),
('Robin Wright', 'robin_wright'),
('Gary Sinise', 'gary_sinise'),
('Michael Clarke Duncan', 'michael_clarke_duncan'),
('David Morse', 'david_morse'),
('Marlon Brando', 'marlon_brando'),
('Al Pacino', 'al_pacino'),
('James Caan', 'james_caann'),
('Ralph Fiennes', 'ralph_fiennes'),
('Juliette Binoche', 'juliette_binoche'),
('Kristin Scott Thomas', 'kristin_scott_thomas'),
('Colin Firth', 'colin_firth'),
('Geoffrey Rush', 'geoffrey_rush'),
('Helena Bonham Carter', 'helena_bonham_carter'),
('Tim Robbins', 'tim_robbins'),
('Morgan Freeman', 'morgan_freeman'),
('Bob Gunton', 'bob_gunton'),
('Liam Neeson', 'liam_neeson'),
('Ben Kingsley', 'ben_kingsley'),
('Brad Pitt', 'brad_pitt'),
('Edward Norton', 'edward_norton'),
('Nicoletta Braschi', 'nicoletta_braschi'),
('Giorgio Cantarini', 'giorgio_cantarini'),
('Robin Williams', 'robin_williams'),
('Ethan Hawke', 'ethan_hawke'),
('Robert Sean Leonard', 'robert_sean_leonard'),
('Bruce Willis', 'bruce_willis'),
('Alan Rickman', 'alan_rickman'),
('Bonnie Bedelia', 'bonnie_bedelia'),
('Tom Hardy', 'tom_hardy'),
('Charlize Theron', 'charlize_theron'),
('Nicholas Hoult', 'nicholas_hoult'),
('Keanu Reeves', 'keanu_reeves'),
('Laurence Fishburne', 'laurence_fishburne'),
('Carrie-Anne Moss', 'carrie_anne_moss'),
('Leonardo DiCaprio', 'leonardo_dicaprio'),
('Joseph Gordon-Levitt', 'joseph_gordon_levitt'),
('Ellen Page', 'ellen_page'),
('Russell Crowe', 'russell_crowe'),
('Joaquin Phoenix', 'joaquin_phoenix'),
('Connie Nielsen', 'connie_nielsen'),
('Uma Thurman', 'uma_thurman'),
('Lucy Liu', 'lucy_liu'),
('Vivica A. Fox', 'vivica_fox'),
('Christian Bale', 'christian_bale'),
('Heath Ledger', 'heath_ledger'),
('Aaron Eckhart', 'aaron_eckhart'),
('Arnold Schwarzenegger', 'arnold_schwarzenegger'),
('Linda Hamilton', 'linda_hamilton'),
('Edward Furlong', 'edward_furlong'),
('Sophie Marceau', 'sophie_marceau'),
('Patrick McGoohan', 'patrick_mcgoohan'),
('Matt Damon', 'matt_damon'),
('Jack Nicholson', 'jack_nicholson');

-- Insert Categories
INSERT INTO Categories (name) VALUES
('Drama'),
('Romance'),
('Fantasy'),
('Crime'),
('War'),
('Biography'),
('History'),
('Action'),
('Thriller'),
('Adventure'),
('Sci-Fi');

-- Insert Films
INSERT INTO Films (title, plot, price, image_name, director_id) VALUES
('Forrest Gump', 'A simple-minded man finds himself in extraordinary situations, meeting historical figures and inadvertently shaping American history, all while pursuing his childhood sweetheart and cherishing life''s simple joys.', 9.99, 'forrest_gump', 1),
('The Green Mile', 'In a 1930s Southern prison, a death row guard''s life takes a profound turn when he encounters a towering inmate with extraordinary powers. Their relationship prompts moral dilemmas and reflections on justice and redemption.', 9.99, 'the_green_mile', 2),
('The Godfather', 'In post-WWII America, a powerful mafia patriarch aims to pass his legacy to his reluctant son. Their journey through the underworld delves into violence, betrayal, and family honor, shaping their destinies amidst profound moral dilemmas.', 9.99, 'the_godfather', 3),
('The English Patient', 'Amidst war''s chaos, a mysterious burn victim recalls a passionate affair in the North African desert. Love and betrayal intertwine, unveiling human connection''s complexities against a backdrop of conflict.', 9.99, 'the_english_patient', 4),
('The King''s Speech', 'During World War II, a hesitant king seeks an unorthodox speech therapist to conquer his stammer and lead his nation. Their evolving bond redefines courage and duty amidst historical turmoil and personal struggles.', 9.99, 'the_kings_speech', 5),
('The Shawshank Redemption', 'In Shawshank prison, a banker, wrongfully convicted, befriends a fellow inmate. Through resilience and hope, they navigate incarceration, proving redemption is attainable even in the darkest confines.', 9.99, 'the_shawshank_redemption', 2),
('Schindler''s List', 'During WWII, Oskar Schindler, a German businessman, saves over a thousand Polish-Jewish refugees from the Holocaust by employing them. His courageous act amid war''s horrors reveals humanity''s potential amidst evil.', 9.99, 'schindlers_list', 6),
('Fight Club', 'In an existential crisis, a disillusioned man forms an underground fight club to escape his mundane life. But as it grows, chaos ensues, questioning societal norms and identity, leading to a shocking revelation about his existence.', 9.99, 'fight_club', 7),
('Life is Beautiful', 'Amidst the Holocaust, a devoted father shields his son from the grim reality of a concentration camp. Through games and love, he turns their ordeal into a journey of hope, proving life''s beauty even in darkness.', 9.99, 'life_is_beautiful', 8),
('Dead Poets Society', 'In a conservative prep school, an inspiring English teacher challenges his students to seize the day and pursue passions. Through poetry and unconventional methods, he instills a love for literature and individuality, altering their perceptions.', 9.99, 'dead_poets_society', 9),
('Die Hard', 'During a hostage situation at a Christmas party, an off-duty cop battles terrorists to save his wife and other captives. Through wit and action, he thwarts their plans, proving one man can make a difference.', 9.99, 'die_hard', 10),
('Mad Max: Fury Road', 'In a post-apocalyptic wasteland, a rogue warrior and a rebel leader team up to escape a tyrant''s grasp. Amidst explosive car chases and battles, they fight for freedom and redemption, showcasing the resilience of the human spirit in a desolate world.', 9.99, 'mad_max_fury_road', 11),
('The Matrix', 'In a dystopian future, a programmer discovers truth and joins rebellion against machines. Through action and inquiry, he fights to free humanity from virtual enslavement, challenging existence and identity.', 9.99, 'the_matrix', 12),
('Inception', 'In a world where dreams can be manipulated, a thief plants an idea into a target''s subconscious. As he delves into layers of dreams, he confronts his past, blurring reality and illusion in a journey of redemption.', 9.99, 'inception', 13),
('Gladiator', 'A betrayed Roman general seeks vengeance against the corrupt emperor who murdered his family and sent him into slavery. Rising through the ranks as a gladiator, he challenges the tyrant''s rule, igniting a epic tale of revenge, honor, and redemption.', 9.99, 'gladiator', 14),
('Kill Bill: Volume 1', 'A former assassin, The Bride, wakes from a coma seeking vengeance against her ex-lover and his deadly team who betrayed her. Armed with deadly skills and a list of targets, she embarks on a relentless quest for justice, leaving a trail of bloodshed.', 9.99, 'kill_bill_volume_1', 15),
('The Dark Knight', 'In Gotham City, Batman faces his greatest challenge against the anarchic Joker. With allies like Commissioner Gordon and Harvey Dent, he navigates through chaos to protect the city from descending into irreversible madness.', 9.99, 'the_dark_knight', 13),
('Terminator 2: Judgment Day', 'In a post-apocalyptic future, a cyborg is sent back in time to protect a boy from a superior model programmed to kill him. As they evade pursuit, they form an unlikely bond while fighting to prevent a catastrophic future war between humans and machines.', 9.99, 'terminator_2_judgment_day', 16),
('Braveheart', 'In medieval Scotland, a fearless warrior rallies his countrymen to fight against English tyranny. Leading with passion and courage, he ignites a rebellion that inspires a nation to stand up for freedom and independence.', 9.99, 'braveheart', 17),
('The Departed', 'In Boston''s underworld, a young cop infiltrates a mob syndicate while a mole within the police feeds information. Tensions rise as both sides race to uncover the traitor, leading to a gripping tale of deception and betrayal.', 9.99, 'the_departed', 18);

-- Insert Films_Categories
INSERT INTO Films_Categories (film_id, category_id) VALUES
(1, 1),
(1, 2),
(2, 1),
(2, 3),
(3, 1),
(3, 4),
(4, 1),
(4, 2),
(4, 5),
(5, 1),
(5, 6),
(5, 7),
(6, 1),
(6, 4),
(7, 1),
(7, 7),
(7, 6),
(8, 1),
(9, 1),
(9, 5),
(10, 1),
(11, 8),
(11, 9),
(12, 8),
(12, 10),
(12, 11),
(13, 8),
(13, 11),
(14, 8),
(14, 10),
(14, 11),
(15, 8),
(15, 10),
(16, 8),
(16, 4),
(16, 9),
(17, 8),
(17, 4),
(18, 8),
(18, 11),
(19, 8),
(19, 6),
(20, 8),
(20, 4);

-- Insert Films_Actors
INSERT INTO Films_Actors (film_id, actor_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 1),
(2, 4),
(2, 5),
(3, 6),
(3, 7),
(3, 8),
(4, 9),
(4, 10),
(4, 11),
(5, 12),
(5, 13),
(5, 14),
(6, 15),
(6, 16),
(6, 17),
(7, 18),
(7, 19),
(7, 9),
(8, 20),
(8, 21),
(8, 14),
(9, 22),
(9, 23),
(10, 24),
(10, 25),
(10, 26),
(11, 27),
(11, 28),
(11, 29),
(12, 30),
(12, 31),
(12, 32),
(13, 33),
(13, 34),
(13, 35),
(14, 36),
(14, 37),
(14, 38),
(15, 39),
(15, 40),
(15, 41),
(16, 42),
(16, 43),
(16, 44),
(17, 45),
(17, 46),
(17, 47),
(18, 48),
(18, 49),
(18, 50),
(19, 51),
(19, 52),
(20, 36),
(20, 53),
(20, 54);
